routes:
  /search: search
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
collections:
  albums: '/albums/{slug}'
  episodes: '/episodes/{slug}'
  songs: '/songs/{slug}'
  videos: '/videos/{slug}'
  wiki: '/wiki/{slug}'
taxonomies:
  wiki-tags: '/wiki/tags/{slug}'
  song-tag: 'songs/tags/{slug}'
  album-tags: 'albums/tags/{slug}'
