routes:
  wiki/tags: wiki/tags
  /search-results: search
  /users: user/index
  '/users/{username}': user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
collections:
  albums: '/albums/{slug}'
  episodes: '/episodes/{slug}'
  songs: '/songs/{slug}'
  videos: '/videos/{slug}'
  wiki: '/wiki/{slug}'
taxonomies:
  tags: '/wiki/tags/{slug}'
