routes:
  /wiki/tags: wiki/tags
  /wiki/search: wiki/search
  /search: search
  /feed:
    layout: feed
    template: feed
    content_type: xml
collections:
  albums: '/albums/{slug}'
  episodes: '/episodes/{slug}'
  songs: '/songs/{slug}'
  videos: '/videos/{slug}'
  wiki: '/wiki/{slug}'
taxonomies:
  tags: '/wiki/tags/{slug}'
